import { FC } from "react"
import styled from "styled-components"
import { IKeyItemProps } from "types/keyboardTypes"

const Keyboard: FC = () => {
    return (
        <KeyboardContainer>
            <KeyboardWrapper>
                <KeyItem>
                    <span>ESC</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>~</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>!</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>@</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>#</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>$</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>%</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>^</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>&</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>*</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>{"("}</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>{")"}</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>{"-"}</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>{"+"}</span>
                    <span></span>
                </KeyItem>
                <KeyItem size={1.6}>
                    <span>{"<>>"}</span>
                    <span></span>
                </KeyItem>
            </KeyboardWrapper>
            <KeyboardWrapper>
                <KeyItem size={1.6}>
                    <span>Tab</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>~</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>!</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>@</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>#</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>$</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>%</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>^</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>&</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>*</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>{"("}</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>{")"}</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>{"-"}</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>{"+"}</span>
                    <span></span>
                </KeyItem>
                <KeyItem size={1}>
                    <span>{"<>>"}</span>
                    <span></span>
                </KeyItem>
            </KeyboardWrapper>
            <KeyboardWrapper>
                <KeyItem size={2.1}>
                    <span>Caps</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>a</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>s</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>d</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>f</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>g</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>h</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>j</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>k</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>l</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>{":"}</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>{'"'}</span>
                    <span></span>
                </KeyItem>
                <KeyItem size={2.75}>
                    <span>{"Enter"}</span>
                    <span></span>
                </KeyItem>
            </KeyboardWrapper>
            <KeyboardWrapper>
                <KeyItem size={2.73}>
                    <span>Shift</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>z</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>x</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>c</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>v</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>b</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>n</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>m</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>{"<"}</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>{">"}</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>{"?"}</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>{"^"}</span>
                    <span></span>
                </KeyItem>
                <KeyItem size={2.14}>
                    <span>{"Shift"}</span>
                    <span></span>
                </KeyItem>
            </KeyboardWrapper>
            <KeyboardWrapper>
                <KeyItem>
                    <span>Fn</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>Ctrl</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>W</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>Alt</span>
                    <span></span>
                </KeyItem>
                <KeyItem size={6.10}>
                    <span></span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>Alt</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>Ctrl</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>{"<>"}</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>{"L"}</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>{">"}</span>
                    <span></span>
                </KeyItem>
                <KeyItem>
                    <span>{"IC"}</span>
                    <span></span>
                </KeyItem>
            </KeyboardWrapper>
        </KeyboardContainer>
    )
}

const KeyboardContainer = styled.div`
     max-width:1180px;
     min-height:100%;
     background: RGB(26, 26, 26);
     margin:0 auto;
     display:flex;
     padding:0.3rem;
     border-radius:3px;
     flex-direction:column;
     gap:.15rem;
     justify-content:center;
     align-items:center;
     font-family: 'Segoe UI', sans-serif;
     font-weight:600;
`
const KeyboardWrapper = styled.div`
    display:flex;
    justify-content:center;
    align-items:center;
    width:100%;
    gap:.15rem;
`
const KeyItem = styled.div<IKeyItemProps>`
    background:#4e4e4e;
    width:100%;
    padding:.2rem;
    width:${props => props.size ? `${props.size * 6}rem` : `${6}rem`};
    height:2.5em;

    display:flex;
    justify-content:flex-start;
    color:white;

    :hover{
        color:#000000;
        background:white;
    }
`

export { Keyboard }